version: '3.8'
x-logging: &default-logging
    driver: journald
    options:
        tag: "{{.Name}}"

x-utility: &default-utility
    image: "alpine:3.11"
    logging: *default-logging
    networks:
        - default

services:
        web:
                image: nginx:1.17.8
                logging: *default-logging
                volumes:
                        - ${PWD}/nginx:/etc/nginx
                restart: on-failure
                stop_grace_period: 30s
                networks:
                    - outside
                    - default
        bitcoin:
                image: lncm/bitcoind:v0.20.0
                logging: *default-logging
                volumes:
                        - ${PWD}/bitcoin:/root/.bitcoin
                        - ${PWD}/bitcoin:/data/.bitcoin
                        - ${PWD}/bitcoin:/data/bitcoin
                restart: on-failure
                stop_grace_period: 20m30s
                networks:
                    - default
        lnd:
                image: lncm/lnd:v0.10.1-experimental
                logging: *default-logging
                volumes:
                        - ${PWD}/lnd:/data/.lnd
                        - ${PWD}/lnd:/root/.lnd
                        - ${PWD}/bitcoin:/root/.bitcoin
                restart: on-failure
                depends_on: [ bitcoin, web ]
                stop_grace_period: 10m30s
                networks:
                    - default
        invoicer:
                image: "lncm/invoicer:v0.8.1"
                depends_on: [ bitcoin, lnd ]
                restart: on-failure
                stop_grace_period: 30s
                volumes:
                        - "${PWD}/invoicer:/root/.lncm"
                        - "${PWD}/invoicer:/data/.lncm"
                        - "${PWD}/invoicer:/lncm"
                        - "${PWD}/invoicer:/data"
                        - "${PWD}/lnd:/lnd"
                networks:
                    - default
        lnd-unlock:
                build: ${PWD}/build/lnd-unlock/
                depends_on: [ lnd ]
                logging: *default-logging
                restart: always
                volumes:
                    - "${PWD}/lnd:/lnd"
                    - "${PWD}/secrets:/secrets"
                networks:
                    - default
        tor:
                build: ${PWD}/build/tor
                restart: on-failure
                logging: *default-logging
                volumes:
                    - "${PWD}/tor/torrc:/etc/tor/torrc"
                    - "${PWD}/tor/data:/var/lib/tor/"
                    - "${PWD}/tor/run:/var/run/tor/"
                networks:
                    - default

networks:
    outside:
        name: Public Visible Network
        external: true
