version: '3.7'
x-logging: &default-logging
    driver: journald
    options:
        tag: "{{.Name}}"

x-utility: &default-utility
    image: "alpine:3.11"
    logging: *default-logging
    network_mode: host

services:
        web:
                image: nginx:1.17.8
                logging: *default-logging
                volumes:
                        - ${PWD}/nginx:/etc/nginx
                restart: on-failure
                network_mode: host
                stop_grace_period: 30s
        bitcoin:
                image: lncm/bitcoind:v0.20.0
                logging: *default-logging
                volumes:
                        - ${PWD}/bitcoin:/root/.bitcoin
                        - ${PWD}/bitcoin:/data/.bitcoin
                        - ${PWD}/bitcoin:/data/bitcoin
                restart: on-failure
                network_mode: host
                stop_grace_period: 15m30s
        lnd:
                image: lncm/lnd:v0.9.2-root-experimental
                logging: *default-logging
                volumes:
                        - ${PWD}/lnd:/data/.lnd
                        - ${PWD}/lnd:/root/.lnd
                        - /var/lib/tor:/var/lib/tor
                        - /run/tor:/run/tor/
                restart: on-failure
                depends_on: [ bitcoin, web ]
                network_mode: host
                stop_grace_period: 5m30s
        invoicer:
                image: "lncm/invoicer:v0.6.6"
                depends_on: [ bitcoin, lnd ]
                restart: on-failure
                network_mode: host
                stop_grace_period: 30s
                volumes:
                        - "${PWD}/invoicer:/root/.lncm"
                        - "${PWD}/invoicer:/lncm"
                        - "${PWD}/lnd:/lnd"
        lnd-unlock:
                build: ${PWD}/build/lnd-unlock/
                depends_on: [ lnd ]
                logging: *default-logging
                restart: always
                volumes:
                    - "${PWD}/lnd:/lnd"
                    - "${PWD}/secrets:/secrets"
                network_mode: host
